In [85]:
# Imports 

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
# Splitting the data 

train_data, test_data = tf.keras.utils.image_dataset_from_directory(
    directory='data',
    label_mode=None,
    batch_size=32,
    image_size=(128, 128),
    validation_split=0.1,
    subset="both",
    seed=1)

Found 17534 files belonging to 1 classes.
Using 15781 files for training.
Using 1753 files for validation.


In [ ]:
# Data Preprocessing

norm = layers.Rescaling(scale=1./255)

def noise(array):
    """
    Adds random noise to each image in the supplied array.
    """

    noise_factor = 0.4
    noisy_array = array + noise_factor * np.random.normal(
        loc=0.0, scale=1.0, size=array.shape
    )

    return np.clip(noisy_array, 0.0, 1.0)

noise_train_data = train_data.unbatch().map(lambda x: x))
norm_train_data = noise_train_data.map(lambda x: norm(x))

norm_test_data = test_data.map(lambda x: norm(x))
noise_test_data = norm_test_data.map(lambda x: noise(x))

In [ ]:
plt.figure(figsize=(5, 5))
for images in train_data.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.axis("off")

In [ ]:
plt.figure(figsize=(5, 5))
for images in norm_train_data.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("float32"))
        plt.axis("off")

In [97]:
for i in train_data.unbatch():
    shape = i.shape
    a = i
print(shape)
a

(128, 128, 3)


<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
array([[[106.99609 , 108.99609 , 103.99609 ],
        [ 94.1517  ,  96.1517  ,  91.1517  ],
        [ 89.540665,  91.540665,  86.540665],
        ...,
        [ 75.4604  ,  63.73384 ,  51.73384 ],
        [ 70.772156,  60.772156,  48.93622 ],
        [ 56.98828 ,  46.98828 ,  36.98828 ]],

       [[106.03516 , 108.03516 , 103.03516 ],
        [ 95.041046,  97.041046,  92.041046],
        [ 87.99539 ,  89.99539 ,  84.99539 ],
        ...,
        [ 77.29457 ,  65.56801 ,  53.56801 ],
        [ 71.43353 ,  61.433533,  49.597595],
        [ 54.035156,  44.035156,  34.035156]],

       [[108.921875, 110.921875, 105.921875],
        [ 99.8139  , 101.8139  ,  96.8139  ],
        [ 91.26419 ,  93.26419 ,  88.26419 ],
        ...,
        [ 75.38835 ,  63.66179 ,  51.66179 ],
        [ 70.78906 ,  60.789062,  48.953125],
        [ 57.01953 ,  47.01953 ,  37.01953 ]],

       ...,

       [[127.96094 , 140.96094 , 133.96094 ],
        [124.

In [99]:
noise(a)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)